CREATE TABLE MATERIAS(
    CODIGO INT,
    ALUMNO VARCHAR(30),
	NOMBRE VARCHAR(30),
    CALIFICACION INT
)

INSERT INTO MATERIAS(CODIGO,ALUMNO,NOMBRE,CALIFICACION) VALUES
(1,'HISTORIA','KIMBERLY GARCIA',8),
(2,'MATEMATICAS','KIMBERLY CHERLYN',9),
(3,'ESPAÑOL','KIMBERLY',10),
(4,'TALLER','JESUS RIOS',6),
(5,'CON_ENERGIA','MANUEL CASTRO',9),
(6,'TUTORIA','LETICIA RIOS',10),
(7,'INGLES','FELIPE GARCIA',9),
(8,'CULTURA DIGITAL','CHERLYN GARCIA',10),
(9,'EDUCACION FISICA','JOVANY CASTRO',10),
(10,'CIENCIAS SOCIALES','JULIO TORRES',6)